### ISSUE TITLE
unable to allocate file descriptor table - out of memory

### ISSUE THREAD

**Issue by arudolph-cxt** [s12v/elasticmq-docker#17]
for no apparent reason (9 out of 32G mem in use) the container is in an endless restart loop

log output:
```
chronext-pa-sqs | 11:26:16.357 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.8) ...
chronext-pa-sqs | 11:26:16.642 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
chronext-pa-sqs | library initialization failed - unable to allocate file descriptor table - out of memorychronext-pa-sqs exited with code 139
chronext-pa-sqs | 11:26:31.522 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.8) ...
chronext-pa-sqs | 11:26:31.828 [elasticmq-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
chronext-pa-sqs | library initialization failed - unable to allocate file descriptor table - out of memorychronext-pa-sqs exited with code 139
chronext-pa-sqs | 11:26:59.419 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.8) ...
chronext-pa-sqs | 11:26:59.728 [elasticmq-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
chronext-pa-sqs | library initialization failed - unable to allocate file descriptor table - out of memorychronext-pa-sqs exited with code 139
chronext-pa-sqs | 11:27:53.068 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.8) ...
chronext-pa-sqs | 11:27:53.361 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
chronext-pa-sqs | library initialization failed - unable to allocate file descriptor table - out of memorychronext-pa-sqs exited with code 139
```
Service definition in docker-compose.yaml:
```
    sqs:
        image: s12v/elasticmq:latest
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "100"
        restart: unless-stopped
        networks:
            - chronext-product-aggregator
```

How can I fix this?
